// Code generated by protoc-gen-go. DO NOT EDIT.
// source: BrokerService.proto

package BrokerService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransferedMessage struct {
	MessageId            *int64   `protobuf:"varint,1,req,name=messageId" json:"messageId,omitempty"`
	CheckSum             *int32   `protobuf:"varint,2,req,name=checkSum" json:"checkSum,omitempty"`
	PayLoadData          []byte   `protobuf:"bytes,3,req,name=payLoadData" json:"payLoadData,omitempty"`
	Flag                 *int32   `protobuf:"varint,4,req,name=flag" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferedMessage) Reset()         { *m = TransferedMessage{} }
func (m *TransferedMessage) String() string { return proto.CompactTextString(m) }
func (*TransferedMessage) ProtoMessage()    {}
func (*TransferedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d575843ca94b2b0, []int{0}
}

func (m *TransferedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferedMessage.Unmarshal(m, b)
}
func (m *TransferedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferedMessage.Marshal(b, m, deterministic)
}
func (m *TransferedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferedMessage.Merge(m, src)
}
func (m *TransferedMessage) XXX_Size() int {
	return xxx_messageInfo_TransferedMessage.Size(m)
}
func (m *TransferedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TransferedMessage proto.InternalMessageInfo

func (m *TransferedMessage) GetMessageId() int64 {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return 0
}

func (m *TransferedMessage) GetCheckSum() int32 {
	if m != nil && m.CheckSum != nil {
		return *m.CheckSum
	}
	return 0
}

func (m *TransferedMessage) GetPayLoadData() []byte {
	if m != nil {
		return m.PayLoadData
	}
	return nil
}

func (m *TransferedMessage) GetFlag() int32 {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return 0
}

type AuthorizedInfo struct {
	VisitAuthorizedToken *int64   `protobuf:"varint,1,req,name=visitAuthorizedToken" json:"visitAuthorizedToken,omitempty"`
	AuthAuthorizedToken  *string  `protobuf:"bytes,2,opt,name=authAuthorizedToken" json:"authAuthorizedToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizedInfo) Reset()         { *m = AuthorizedInfo{} }
func (m *AuthorizedInfo) String() string { return proto.CompactTextString(m) }
func (*AuthorizedInfo) ProtoMessage()    {}
func (*AuthorizedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d575843ca94b2b0, []int{1}
}

func (m *AuthorizedInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizedInfo.Unmarshal(m, b)
}
func (m *AuthorizedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizedInfo.Marshal(b, m, deterministic)
}
func (m *AuthorizedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizedInfo.Merge(m, src)
}
func (m *AuthorizedInfo) XXX_Size() int {
	return xxx_messageInfo_AuthorizedInfo.Size(m)
}
func (m *AuthorizedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizedInfo proto.InternalMessageInfo

func (m *AuthorizedInfo) GetVisitAuthorizedToken() int64 {
	if m != nil && m.VisitAuthorizedToken != nil {
		return *m.VisitAuthorizedToken
	}
	return 0
}

func (m *AuthorizedInfo) GetAuthAuthorizedToken() string {
	if m != nil && m.AuthAuthorizedToken != nil {
		return *m.AuthAuthorizedToken
	}
	return ""
}

type SendMessageRequestP2B struct {
	ClientId             *string         `protobuf:"bytes,1,req,name=clientId" json:"clientId,omitempty"`
	TopicName            *string         `protobuf:"bytes,2,req,name=topicName" json:"topicName,omitempty"`
	PartitionId          *int32          `protobuf:"varint,3,req,name=partitionId" json:"partitionId,omitempty"`
	Data                 []byte          `protobuf:"bytes,4,req,name=data" json:"data,omitempty"`
	Flag                 *int32          `protobuf:"varint,5,req,name=flag" json:"flag,omitempty"`
	CheckSum             *int32          `protobuf:"varint,6,req,name=checkSum" json:"checkSum,omitempty"`
	SentAddr             *int32          `protobuf:"varint,7,req,name=sentAddr" json:"sentAddr,omitempty"`
	MsgType              *string         `protobuf:"bytes,8,opt,name=msgType" json:"msgType,omitempty"`
	MsgTime              *string         `protobuf:"bytes,9,opt,name=msgTime" json:"msgTime,omitempty"`
	AuthInfo             *AuthorizedInfo `protobuf:"bytes,10,opt,name=authInfo" json:"authInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SendMessageRequestP2B) Reset()         { *m = SendMessageRequestP2B{} }
func (m *SendMessageRequestP2B) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequestP2B) ProtoMessage()    {}
func (*SendMessageRequestP2B) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d575843ca94b2b0, []int{2}
}

func (m *SendMessageRequestP2B) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequestP2B.Unmarshal(m, b)
}
func (m *SendMessageRequestP2B) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequestP2B.Marshal(b, m, deterministic)
}
func (m *SendMessageRequestP2B) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequestP2B.Merge(m, src)
}
func (m *SendMessageRequestP2B) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequestP2B.Size(m)
}
func (m *SendMessageRequestP2B) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequestP2B.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequestP2B proto.InternalMessageInfo

func (m *SendMessageRequestP2B) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *SendMessageRequestP2B) GetTopicName() string {
	if m != nil && m.TopicName != nil {
		return *m.TopicName
	}
	return ""
}

func (m *SendMessageRequestP2B) GetPartitionId() int32 {
	if m != nil && m.PartitionId != nil {
		return *m.PartitionId
	}
	return 0
}

func (m *SendMessageRequestP2B) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SendMessageRequestP2B) GetFlag() int32 {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return 0
}

func (m *SendMessageRequestP2B) GetCheckSum() int32 {
	if m != nil && m.CheckSum != nil {
		return *m.CheckSum
	}
	return 0
}

func (m *SendMessageRequestP2B) GetSentAddr() int32 {
	if m != nil && m.SentAddr != nil {
		return *m.SentAddr
	}
	return 0
}

func (m *SendMessageRequestP2B) GetMsgType() string {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return ""
}

func (m *SendMessageRequestP2B) GetMsgTime() string {
	if m != nil && m.MsgTime != nil {
		return *m.MsgTime
	}
	return ""
}

func (m *SendMessageRequestP2B) GetAuthInfo() *AuthorizedInfo {
	if m != nil {
		return m.AuthInfo
	}
	return nil
}

type SendMessageResponseB2P struct {
	Success              *bool    `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	ErrMsg               *string  `protobuf:"bytes,3,req,name=errMsg" json:"errMsg,omitempty"`
	RequireAuth          *bool    `protobuf:"varint,4,opt,name=requireAuth" json:"requireAuth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResponseB2P) Reset()         { *m = SendMessageResponseB2P{} }
func (m *SendMessageResponseB2P) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponseB2P) ProtoMessage()    {}
func (*SendMessageResponseB2P) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d575843ca94b2b0, []int{3}
}

func (m *SendMessageResponseB2P) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResponseB2P.Unmarshal(m, b)
}
func (m *SendMessageResponseB2P) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResponseB2P.Marshal(b, m, deterministic)
}
func (m *SendMessageResponseB2P) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResponseB2P.Merge(m, src)
}
func (m *SendMessageResponseB2P) XXX_Size() int {
	return xxx_messageInfo_SendMessageResponseB2P.Size(m)
}
func (m *SendMessageResponseB2P) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResponseB2P.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResponseB2P proto.InternalMessageInfo

func (m *SendMessageResponseB2P) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *SendMessageResponseB2P) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *SendMessageResponseB2P) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

func (m *SendMessageResponseB2P) GetRequireAuth() bool {
	if m != nil && m.RequireAuth != nil {
		return *m.RequireAuth
	}
	return false
}

type RegisterRequestC2B struct {
	OpType               *int32          `protobuf:"varint,1,req,name=opType" json:"opType,omitempty"`
	ClientId             *string         `protobuf:"bytes,2,req,name=clientId" json:"clientId,omitempty"`
	GroupName            *string         `protobuf:"bytes,3,req,name=groupName" json:"groupName,omitempty"`
	TopicName            *string         `protobuf:"bytes,4,req,name=topicName" json:"topicName,omitempty"`
	PartitionId          *int32          `protobuf:"varint,5,req,name=partitionId" json:"partitionId,omitempty"`
	ReadStatus           *int32          `protobuf:"varint,6,req,name=readStatus" json:"readStatus,omitempty"`
	FilterCondStr        []string        `protobuf:"bytes,7,rep,name=filterCondStr" json:"filterCondStr,omitempty"`
	CurrOffset           *int64          `protobuf:"varint,8,opt,name=currOffset" json:"currOffset,omitempty"`
	SessionKey           *string         `protobuf:"bytes,9,opt,name=sessionKey" json:"sessionKey,omitempty"`
	SessionTime          *int64          `protobuf:"varint,10,opt,name=sessionTime" json:"sessionTime,omitempty"`
	SsdStoreId           *int64          `protobuf:"varint,11,opt,name=ssdStoreId" json:"ssdStoreId,omitempty"`
	QryPriorityId        *int32          `protobuf:"varint,12,opt,name=qryPriorityId" json:"qryPriorityId,omitempty"`
	AuthInfo             *AuthorizedInfo `protobuf:"bytes,13,opt,name=authInfo" json:"authInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RegisterRequestC2B) Reset()         { *m = RegisterRequestC2B{} }
func (m *RegisterRequestC2B) String() string { return proto.CompactTextString(m) }
func (*RegisterRequestC2B) ProtoMessage()    {}
func (*RegisterRequestC2B) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d575843ca94b2b0, []int{4}
}

func (m *RegisterRequestC2B) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequestC2B.Unmarshal(m, b)
}
func (m *RegisterRequestC2B) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequestC2B.Marshal(b, m, deterministic)
}
func (m *RegisterRequestC2B) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequestC2B.Merge(m, src)
}
func (m *RegisterRequestC2B) XXX_Size() int {
	return xxx_messageInfo_RegisterRequestC2B.Size(m)
}
func (m *RegisterRequestC2B) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequestC2B.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequestC2B proto.InternalMessageInfo

func (m *RegisterRequestC2B) GetOpType() int32 {
	if m != nil && m.OpType != nil {
		return *m.OpType
	}
	return 0
}

func (m *RegisterRequestC2B) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *RegisterRequestC2B) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

func (m *RegisterRequestC2B) GetTopicName() string {
	if m != nil && m.TopicName != nil {
		return *m.TopicName
	}
	return ""
}

func (m *RegisterRequestC2B) GetPartitionId() int32 {
	if m != nil && m.PartitionId != nil {
		return *m.PartitionId
	}
	return 0
}

func (m *RegisterRequestC2B) GetReadStatus() int32 {
	if m != nil && m.ReadStatus != nil {
		return *m.ReadStatus
	}
	return 0
}

func (m *RegisterRequestC2B) GetFilterCondStr() []string {
	if m != nil {
		return m.FilterCondStr
	}
	return nil
}

func (m *RegisterRequestC2B) GetCurrOffset() int64 {
	if m != nil && m.CurrOffset != nil {
		return *m.CurrOffset
	}
	return 0
}

func (m *RegisterRequestC2B) GetSessionKey() string {
	if m != nil && m.SessionKey != nil {
		return *m.SessionKey
	}
	return ""
}

func (m *RegisterRequestC2B) GetSessionTime() int64 {
	if m != nil && m.SessionTime != nil {
		return *m.SessionTime
	}
	return 0
}

func (m *RegisterRequestC2B) GetSsdStoreId() int64 {
	if m != nil && m.SsdStoreId != nil {
		return *m.SsdStoreId
	}
	return 0
}

func (m *RegisterRequestC2B) GetQryPriorityId() int32 {
	if m != nil && m.QryPriorityId != nil {
		return *m.QryPriorityId
	}
	return 0
}

func (m *RegisterRequestC2B) GetAuthInfo() *AuthorizedInfo {
	if m != nil {
		return m.AuthInfo
	}
	return nil
}

type RegisterResponseB2C struct {
	Success              *bool    `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	ErrMsg               *string  `protobuf:"bytes,3,req,name=errMsg" json:"errMsg,omitempty"`
	CurrOffset           *int64   `protobuf:"varint,4,opt,name=currOffset" json:"currOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponseB2C) Reset()         { *m = RegisterResponseB2C{} }
func (m *RegisterResponseB2C) String() string { return proto.CompactTextString(m) }
func (*RegisterResponseB2C) ProtoMessage()    {}
func (*RegisterResponseB2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d575843ca94b2b0, []int{5}
}

func (m *RegisterResponseB2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponseB2C.Unmarshal(m, b)
}
func (m *RegisterResponseB2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponseB2C.Marshal(b, m, deterministic)
}
func (m *RegisterResponseB2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponseB2C.Merge(m, src)
}
func (m *RegisterResponseB2C) XXX_Size() int {
	return xxx_messageInfo_RegisterResponseB2C.Size(m)
}
func (m *RegisterResponseB2C) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponseB2C.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponseB2C proto.InternalMessageInfo

func (m *RegisterResponseB2C) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *RegisterResponseB2C) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *RegisterResponseB2C) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

func (m *RegisterResponseB2C) GetCurrOffset() int64 {
	if m != nil && m.CurrOffset != nil {
		return *m.CurrOffset
	}
	return 0
}

type HeartBeatRequestC2B struct {
	ClientId   *string `protobuf:"bytes,1,req,name=clientId" json:"clientId,omitempty"`
	GroupName  *string `protobuf:"bytes,2,req,name=groupName" json:"groupName,omitempty"`
	ReadStatus *int32  `protobuf:"varint,3,req,name=readStatus" json:"readStatus,omitempty"`
	// brokerId:host:port:topic:partitionId:delayTimeStamp
	PartitionInfo        []string        `protobuf:"bytes,4,rep,name=partitionInfo" json:"partitionInfo,omitempty"`
	SsdStoreId           *int64          `protobuf:"varint,5,opt,name=ssdStoreId" json:"ssdStoreId,omitempty"`
	QryPriorityId        *int32          `protobuf:"varint,6,opt,name=qryPriorityId" json:"qryPriorityId,omitempty"`
	AuthInfo             *AuthorizedInfo `protobuf:"bytes,7,opt,name=authInfo" json:"authInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HeartBeatRequestC2B) Reset()         { *m = HeartBeatRequestC2B{} }
func (m *HeartBeatRequestC2B) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRequestC2B) ProtoMessage()    {}
func (*HeartBeatRequestC2B) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d575843ca94b2b0, []int{6}
}

func (m *HeartBeatRequestC2B) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRequestC2B.Unmarshal(m, b)
}
func (m *HeartBeatRequestC2B) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRequestC2B.Marshal(b, m, deterministic)
}
func (m *HeartBeatRequestC2B) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRequestC2B.Merge(m, src)
}
func (m *HeartBeatRequestC2B) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRequestC2B.Size(m)
}
func (m *HeartBeatRequestC2B) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRequestC2B.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRequestC2B proto.InternalMessageInfo

func (m *HeartBeatRequestC2B) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *HeartBeatRequestC2B) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

func (m *HeartBeatRequestC2B) GetReadStatus() int32 {
	if m != nil && m.ReadStatus != nil {
		return *m.ReadStatus
	}
	return 0
}

func (m *HeartBeatRequestC2B) GetPartitionInfo() []string {
	if m != nil {
		return m.PartitionInfo
	}
	return nil
}

func (m *HeartBeatRequestC2B) GetSsdStoreId() int64 {
	if m != nil && m.SsdStoreId != nil {
		return *m.SsdStoreId
	}
	return 0
}

func (m *HeartBeatRequestC2B) GetQryPriorityId() int32 {
	if m != nil && m.QryPriorityId != nil {
		return *m.QryPriorityId
	}
	return 0
}

func (m *HeartBeatRequestC2B) GetAuthInfo() *AuthorizedInfo {
	if m != nil {
		return m.AuthInfo
	}
	return nil
}

type HeartBeatResponseB2C struct {
	Success        *bool   `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	ErrCode        *int32  `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	ErrMsg         *string `protobuf:"bytes,3,req,name=errMsg" json:"errMsg,omitempty"`
	HasPartFailure *bool   `protobuf:"varint,4,opt,name=hasPartFailure" json:"hasPartFailure,omitempty"`
	// failCode:brokerId:host:port:topic:partitionId:delayTimeStamp
	FailureInfo          []string `protobuf:"bytes,5,rep,name=failureInfo" json:"failureInfo,omitempty"`
	RequireAuth          *bool    `protobuf:"varint,6,opt,name=requireAuth" json:"requireAuth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatResponseB2C) Reset()         { *m = HeartBeatResponseB2C{} }
func (m *HeartBeatResponseB2C) String() string { return proto.CompactTextString(m) }
func (*HeartBeatResponseB2C) ProtoMessage()    {}
func (*HeartBeatResponseB2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d575843ca94b2b0, []int{7}
}

func (m *HeartBeatResponseB2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatResponseB2C.Unmarshal(m, b)
}
func (m *HeartBeatResponseB2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatResponseB2C.Marshal(b, m, deterministic)
}
func (m *HeartBeatResponseB2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatResponseB2C.Merge(m, src)
}
func (m *HeartBeatResponseB2C) XXX_Size() int {
	return xxx_messageInfo_HeartBeatResponseB2C.Size(m)
}
func (m *HeartBeatResponseB2C) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatResponseB2C.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatResponseB2C proto.InternalMessageInfo

func (m *HeartBeatResponseB2C) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *HeartBeatResponseB2C) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *HeartBeatResponseB2C) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

func (m *HeartBeatResponseB2C) GetHasPartFailure() bool {
	if m != nil && m.HasPartFailure != nil {
		return *m.HasPartFailure
	}
	return false
}

func (m *HeartBeatResponseB2C) GetFailureInfo() []string {
	if m != nil {
		return m.FailureInfo
	}
	return nil
}

func (m *HeartBeatResponseB2C) GetRequireAuth() bool {
	if m != nil && m.RequireAuth != nil {
		return *m.RequireAuth
	}
	return false
}

type GetMessageRequestC2B struct {
	ClientId             *string  `protobuf:"bytes,1,req,name=clientId" json:"clientId,omitempty"`
	PartitionId          *int32   `protobuf:"varint,2,req,name=partitionId" json:"partitionId,omitempty"`
	GroupName            *string  `protobuf:"bytes,3,req,name=groupName" json:"groupName,omitempty"`
	TopicName            *string  `protobuf:"bytes,4,req,name=topicName" json:"topicName,omitempty"`
	LastPackConsumed     *bool    `protobuf:"varint,5,opt,name=lastPackConsumed" json:"lastPackConsumed,omitempty"`
	ManualCommitOffset   *bool    `protobuf:"varint,6,opt,name=manualCommitOffset" json:"manualCommitOffset,omitempty"`
	EscFlowCtrl          *bool    `protobuf:"varint,7,opt,name=escFlowCtrl" json:"escFlowCtrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageRequestC2B) Reset()         { *m = GetMessageRequestC2B{} }
func (m *GetMessageRequestC2B) String() string { return proto.CompactTextString(m) }
func (*GetMessageRequestC2B) ProtoMessage()    {}
func (*GetMessageRequestC2B) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d575843ca94b2b0, []int{8}
}

func (m *GetMessageRequestC2B) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageRequestC2B.Unmarshal(m, b)
}
func (m *GetMessageRequestC2B) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageRequestC2B.Marshal(b, m, deterministic)
}
func (m *GetMessageRequestC2B) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageRequestC2B.Merge(m, src)
}
func (m *GetMessageRequestC2B) XXX_Size() int {
	return xxx_messageInfo_GetMessageRequestC2B.Size(m)
}
func (m *GetMessageRequestC2B) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageRequestC2B.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageRequestC2B proto.InternalMessageInfo

func (m *GetMessageRequestC2B) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *GetMessageRequestC2B) GetPartitionId() int32 {
	if m != nil && m.PartitionId != nil {
		return *m.PartitionId
	}
	return 0
}

func (m *GetMessageRequestC2B) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

func (m *GetMessageRequestC2B) GetTopicName() string {
	if m != nil && m.TopicName != nil {
		return *m.TopicName
	}
	return ""
}

func (m *GetMessageRequestC2B) GetLastPackConsumed() bool {
	if m != nil && m.LastPackConsumed != nil {
		return *m.LastPackConsumed
	}
	return false
}

func (m *GetMessageRequestC2B) GetManualCommitOffset() bool {
	if m != nil && m.ManualCommitOffset != nil {
		return *m.ManualCommitOffset
	}
	return false
}

func (m *GetMessageRequestC2B) GetEscFlowCtrl() bool {
	if m != nil && m.EscFlowCtrl != nil {
		return *m.EscFlowCtrl
	}
	return false
}

type GetMessageResponseB2C struct {
	Success              *bool                `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	ErrCode              *int32               `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	ErrMsg               *string              `protobuf:"bytes,3,opt,name=errMsg" json:"errMsg,omitempty"`
	Messages             []*TransferedMessage `protobuf:"bytes,4,rep,name=messages" json:"messages,omitempty"`
	CurrOffset           *int64               `protobuf:"varint,5,opt,name=currOffset" json:"currOffset,omitempty"`
	MinLimitTime         *int32               `protobuf:"varint,6,opt,name=minLimitTime" json:"minLimitTime,omitempty"`
	EscFlowCtrl          *bool                `protobuf:"varint,7,opt,name=escFlowCtrl" json:"escFlowCtrl,omitempty"`
	CurrDataDlt          *int64               `protobuf:"varint,8,opt,name=currDataDlt" json:"currDataDlt,omitempty"`
	RequireSlow          *bool                `protobuf:"varint,9,opt,name=requireSlow" json:"requireSlow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetMessageResponseB2C) Reset()         { *m = GetMessageResponseB2C{} }
func (m *GetMessageResponseB2C) String() string { return proto.CompactTextString(m) }
func (*GetMessageResponseB2C) ProtoMessage()    {}
func (*GetMessageResponseB2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d575843ca94b2b0, []int{9}
}

func (m *GetMessageResponseB2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageResponseB2C.Unmarshal(m, b)
}
func (m *GetMessageResponseB2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageResponseB2C.Marshal(b, m, deterministic)
}
func (m *GetMessageResponseB2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageResponseB2C.Merge(m, src)
}
func (m *GetMessageResponseB2C) XXX_Size() int {
	return xxx_messageInfo_GetMessageResponseB2C.Size(m)
}
func (m *GetMessageResponseB2C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageResponseB2C.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageResponseB2C proto.InternalMessageInfo

func (m *GetMessageResponseB2C) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *GetMessageResponseB2C) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *GetMessageResponseB2C) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

func (m *GetMessageResponseB2C) GetMessages() []*TransferedMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *GetMessageResponseB2C) GetCurrOffset() int64 {
	if m != nil && m.CurrOffset != nil {
		return *m.CurrOffset
	}
	return 0
}

func (m *GetMessageResponseB2C) GetMinLimitTime() int32 {
	if m != nil && m.MinLimitTime != nil {
		return *m.MinLimitTime
	}
	return 0
}

func (m *GetMessageResponseB2C) GetEscFlowCtrl() bool {
	if m != nil && m.EscFlowCtrl != nil {
		return *m.EscFlowCtrl
	}
	return false
}

func (m *GetMessageResponseB2C) GetCurrDataDlt() int64 {
	if m != nil && m.CurrDataDlt != nil {
		return *m.CurrDataDlt
	}
	return 0
}

func (m *GetMessageResponseB2C) GetRequireSlow() bool {
	if m != nil && m.RequireSlow != nil {
		return *m.RequireSlow
	}
	return false
}

type CommitOffsetRequestC2B struct {
	ClientId             *string  `protobuf:"bytes,1,req,name=clientId" json:"clientId,omitempty"`
	TopicName            *string  `protobuf:"bytes,2,req,name=topicName" json:"topicName,omitempty"`
	PartitionId          *int32   `protobuf:"varint,3,req,name=partitionId" json:"partitionId,omitempty"`
	GroupName            *string  `protobuf:"bytes,4,req,name=groupName" json:"groupName,omitempty"`
	LastPackConsumed     *bool    `protobuf:"varint,5,opt,name=lastPackConsumed" json:"lastPackConsumed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitOffsetRequestC2B) Reset()         { *m = CommitOffsetRequestC2B{} }
func (m *CommitOffsetRequestC2B) String() string { return proto.CompactTextString(m) }
func (*CommitOffsetRequestC2B) ProtoMessage()    {}
func (*CommitOffsetRequestC2B) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d575843ca94b2b0, []int{10}
}

func (m *CommitOffsetRequestC2B) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitOffsetRequestC2B.Unmarshal(m, b)
}
func (m *CommitOffsetRequestC2B) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitOffsetRequestC2B.Marshal(b, m, deterministic)
}
func (m *CommitOffsetRequestC2B) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitOffsetRequestC2B.Merge(m, src)
}
func (m *CommitOffsetRequestC2B) XXX_Size() int {
	return xxx_messageInfo_CommitOffsetRequestC2B.Size(m)
}
func (m *CommitOffsetRequestC2B) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitOffsetRequestC2B.DiscardUnknown(m)
}

var xxx_messageInfo_CommitOffsetRequestC2B proto.InternalMessageInfo

func (m *CommitOffsetRequestC2B) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *CommitOffsetRequestC2B) GetTopicName() string {
	if m != nil && m.TopicName != nil {
		return *m.TopicName
	}
	return ""
}

func (m *CommitOffsetRequestC2B) GetPartitionId() int32 {
	if m != nil && m.PartitionId != nil {
		return *m.PartitionId
	}
	return 0
}

func (m *CommitOffsetRequestC2B) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

func (m *CommitOffsetRequestC2B) GetLastPackConsumed() bool {
	if m != nil && m.LastPackConsumed != nil {
		return *m.LastPackConsumed
	}
	return false
}

type CommitOffsetResponseB2C struct {
	Success              *bool    `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	ErrMsg               *string  `protobuf:"bytes,3,req,name=errMsg" json:"errMsg,omitempty"`
	CurrOffset           *int64   `protobuf:"varint,4,opt,name=currOffset" json:"currOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitOffsetResponseB2C) Reset()         { *m = CommitOffsetResponseB2C{} }
func (m *CommitOffsetResponseB2C) String() string { return proto.CompactTextString(m) }
func (*CommitOffsetResponseB2C) ProtoMessage()    {}
func (*CommitOffsetResponseB2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d575843ca94b2b0, []int{11}
}

func (m *CommitOffsetResponseB2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitOffsetResponseB2C.Unmarshal(m, b)
}
func (m *CommitOffsetResponseB2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitOffsetResponseB2C.Marshal(b, m, deterministic)
}
func (m *CommitOffsetResponseB2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitOffsetResponseB2C.Merge(m, src)
}
func (m *CommitOffsetResponseB2C) XXX_Size() int {
	return xxx_messageInfo_CommitOffsetResponseB2C.Size(m)
}
func (m *CommitOffsetResponseB2C) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitOffsetResponseB2C.DiscardUnknown(m)
}

var xxx_messageInfo_CommitOffsetResponseB2C proto.InternalMessageInfo

func (m *CommitOffsetResponseB2C) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *CommitOffsetResponseB2C) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *CommitOffsetResponseB2C) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

func (m *CommitOffsetResponseB2C) GetCurrOffset() int64 {
	if m != nil && m.CurrOffset != nil {
		return *m.CurrOffset
	}
	return 0
}

func init() {
	proto.RegisterType((*TransferedMessage)(nil), "TransferedMessage")
	proto.RegisterType((*AuthorizedInfo)(nil), "AuthorizedInfo")
	proto.RegisterType((*SendMessageRequestP2B)(nil), "SendMessageRequestP2B")
	proto.RegisterType((*SendMessageResponseB2P)(nil), "SendMessageResponseB2P")
	proto.RegisterType((*RegisterRequestC2B)(nil), "RegisterRequestC2B")
	proto.RegisterType((*RegisterResponseB2C)(nil), "RegisterResponseB2C")
	proto.RegisterType((*HeartBeatRequestC2B)(nil), "HeartBeatRequestC2B")
	proto.RegisterType((*HeartBeatResponseB2C)(nil), "HeartBeatResponseB2C")
	proto.RegisterType((*GetMessageRequestC2B)(nil), "GetMessageRequestC2B")
	proto.RegisterType((*GetMessageResponseB2C)(nil), "GetMessageResponseB2C")
	proto.RegisterType((*CommitOffsetRequestC2B)(nil), "CommitOffsetRequestC2B")
	proto.RegisterType((*CommitOffsetResponseB2C)(nil), "CommitOffsetResponseB2C")
}

func init() {
	proto.RegisterFile("BrokerService.proto", fileDescriptor_3d575843ca94b2b0)
}

var fileDescriptor_3d575843ca94b2b0 = []byte{
	// 910 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xd6, 0x38, 0x49, 0xeb, 0x9c, 0x76, 0x17, 0x70, 0xbb, 0xc5, 0x5a, 0x21, 0x14, 0x59, 0x08,
	0x45, 0x20, 0x2c, 0x94, 0x37, 0xd8, 0x64, 0x59, 0xb6, 0x62, 0x17, 0xa2, 0x49, 0x5f, 0x60, 0x6a,
	0x9f, 0x24, 0xa3, 0xda, 0x9e, 0x74, 0x66, 0xdc, 0x55, 0xb8, 0x43, 0x08, 0xb4, 0x57, 0x3c, 0x03,
	0x0f, 0xc1, 0x2d, 0x48, 0xbc, 0x00, 0xcf, 0x84, 0x66, 0xec, 0xc4, 0x3f, 0xa9, 0x64, 0xd0, 0x16,
	0x71, 0x37, 0xe7, 0x3b, 0xf6, 0xcc, 0x39, 0xdf, 0xf7, 0xcd, 0xd1, 0xc0, 0xd9, 0x54, 0x8a, 0x1b,
	0x94, 0x0b, 0x94, 0x77, 0x3c, 0xc2, 0x70, 0x23, 0x85, 0x16, 0xc1, 0x8f, 0x04, 0x3e, 0xb8, 0x92,
	0x2c, 0x53, 0x4b, 0x94, 0x18, 0xbf, 0x46, 0xa5, 0xd8, 0x0a, 0xbd, 0x8f, 0x60, 0x98, 0x16, 0xcb,
	0xcb, 0xd8, 0x27, 0x23, 0x67, 0xdc, 0xa3, 0x15, 0xe0, 0x3d, 0x05, 0x37, 0x5a, 0x63, 0x74, 0xb3,
	0xc8, 0x53, 0xdf, 0x19, 0x39, 0xe3, 0x01, 0xdd, 0xc7, 0xde, 0x08, 0x4e, 0x36, 0x6c, 0xfb, 0x4a,
	0xb0, 0xf8, 0x39, 0xd3, 0xcc, 0xef, 0x8d, 0x9c, 0xf1, 0x29, 0xad, 0x43, 0x9e, 0x07, 0xfd, 0x65,
	0xc2, 0x56, 0x7e, 0xdf, 0xfe, 0x69, 0xd7, 0xc1, 0x1d, 0x3c, 0x7e, 0x96, 0xeb, 0xb5, 0x90, 0xfc,
	0x7b, 0x8c, 0x2f, 0xb3, 0xa5, 0xf0, 0x26, 0x70, 0x7e, 0xc7, 0x15, 0xd7, 0x15, 0x7c, 0x25, 0x6e,
	0x30, 0x2b, 0x8b, 0xb9, 0x37, 0xe7, 0x7d, 0x09, 0x67, 0x2c, 0xd7, 0xeb, 0xf6, 0x2f, 0xce, 0x88,
	0x8c, 0x87, 0xf4, 0xbe, 0x54, 0xf0, 0x9b, 0x03, 0x4f, 0x16, 0x98, 0xed, 0xfa, 0xa6, 0x78, 0x9b,
	0xa3, 0xd2, 0xf3, 0xc9, 0xd4, 0xf6, 0x98, 0x70, 0xcc, 0x74, 0x49, 0xc0, 0x90, 0xee, 0x63, 0xc3,
	0x8e, 0x16, 0x1b, 0x1e, 0x7d, 0xcb, 0x52, 0xb4, 0x04, 0x0c, 0x69, 0x05, 0x14, 0x0c, 0x48, 0xcd,
	0x35, 0x17, 0xd9, 0x65, 0x6c, 0x19, 0x18, 0xd0, 0x3a, 0x64, 0x18, 0x88, 0x0d, 0x39, 0x7d, 0x4b,
	0x8e, 0x5d, 0xef, 0x59, 0x19, 0x54, 0xac, 0x34, 0x78, 0x3e, 0x6a, 0xf1, 0xfc, 0x14, 0x5c, 0x85,
	0x99, 0x7e, 0x16, 0xc7, 0xd2, 0x3f, 0x2e, 0x72, 0xbb, 0xd8, 0xf3, 0xe1, 0x38, 0x55, 0xab, 0xab,
	0xed, 0x06, 0x7d, 0xd7, 0xf6, 0xbe, 0x0b, 0x77, 0x19, 0x9e, 0xa2, 0x3f, 0xac, 0x32, 0x3c, 0x45,
	0xef, 0x73, 0x70, 0x0d, 0x41, 0x86, 0x7b, 0x1f, 0x46, 0x64, 0x7c, 0x32, 0x79, 0x2f, 0x6c, 0x4a,
	0x42, 0xf7, 0x1f, 0x04, 0x3f, 0x13, 0xb8, 0x68, 0xd0, 0xa6, 0x36, 0x22, 0x53, 0x38, 0x9d, 0xcc,
	0xcd, 0x09, 0x2a, 0x8f, 0x22, 0x54, 0xca, 0xd2, 0xe6, 0xd2, 0x5d, 0x68, 0x32, 0x28, 0xe5, 0x4c,
	0xc4, 0x58, 0x9a, 0x66, 0x17, 0x7a, 0x17, 0x70, 0x84, 0x52, 0xbe, 0x56, 0x2b, 0x4b, 0xd6, 0x90,
	0x96, 0x91, 0x61, 0x52, 0xe2, 0x6d, 0xce, 0x25, 0x9a, 0x4a, 0xfc, 0xfe, 0x88, 0x8c, 0x5d, 0x5a,
	0x87, 0x82, 0x3f, 0x7b, 0xe0, 0x51, 0x5c, 0x71, 0xa5, 0x51, 0x96, 0xe2, 0xcd, 0x26, 0x53, 0xb3,
	0xa1, 0xd8, 0xd8, 0xfe, 0x89, 0x3d, 0xa9, 0x8c, 0x1a, 0xa2, 0x3a, 0x87, 0xa2, 0xae, 0xa4, 0xc8,
	0x37, 0x56, 0xd4, 0xa2, 0x8e, 0x0a, 0x68, 0x4a, 0xde, 0xef, 0x90, 0x7c, 0x70, 0x28, 0xf9, 0xc7,
	0x00, 0x12, 0x59, 0xbc, 0xd0, 0x4c, 0xe7, 0xaa, 0x14, 0xb3, 0x86, 0x78, 0x9f, 0xc0, 0xa3, 0x25,
	0x4f, 0x34, 0xca, 0x99, 0xc8, 0xe2, 0x85, 0x36, 0x9a, 0xf6, 0xc6, 0x43, 0xda, 0x04, 0xcd, 0x2e,
	0x51, 0x2e, 0xe5, 0x77, 0xcb, 0xa5, 0x42, 0x6d, 0xb5, 0xed, 0xd1, 0x1a, 0x62, 0xf2, 0x0a, 0x95,
	0xe2, 0x22, 0xfb, 0x06, 0xb7, 0xa5, 0xc2, 0x35, 0xc4, 0xd4, 0x59, 0x46, 0xd6, 0x02, 0x60, 0x37,
	0xa8, 0x43, 0x76, 0x07, 0x15, 0x2f, 0xb4, 0x90, 0xe6, 0xe6, 0x9f, 0x14, 0x27, 0x54, 0x88, 0xa9,
	0xf3, 0x56, 0x6e, 0xe7, 0x92, 0x0b, 0xc9, 0xf5, 0xf6, 0x32, 0xf6, 0x4f, 0x47, 0x64, 0x3c, 0xa0,
	0x4d, 0xb0, 0x61, 0xa6, 0x47, 0x5d, 0x66, 0xfa, 0x81, 0xc0, 0x59, 0xa5, 0xe1, 0xce, 0x49, 0xb3,
	0x07, 0x75, 0x52, 0x93, 0xb8, 0x7e, 0x9b, 0xb8, 0xe0, 0xad, 0x03, 0x67, 0x2f, 0x91, 0x49, 0x3d,
	0x45, 0xa6, 0x6b, 0x46, 0xea, 0x98, 0x02, 0x95, 0x61, 0x9c, 0xb6, 0x61, 0x9a, 0x82, 0xf7, 0xee,
	0x13, 0xbc, 0xf2, 0x87, 0xe1, 0xa9, 0x5f, 0x08, 0xde, 0x00, 0x5b, 0x72, 0x0c, 0xba, 0xe5, 0x38,
	0xea, 0x92, 0xe3, 0xb8, 0x4b, 0x8e, 0xbf, 0x08, 0x9c, 0xd7, 0xa8, 0xf8, 0x6f, 0xf4, 0xf8, 0x14,
	0x1e, 0xaf, 0x99, 0x9a, 0x33, 0xa9, 0x5f, 0x30, 0x9e, 0xe4, 0x12, 0xcb, 0xcb, 0xdd, 0x42, 0x8d,
	0x61, 0x97, 0xc5, 0xd2, 0x16, 0x3f, 0xb0, 0x1c, 0xd5, 0xa1, 0xf6, 0x8c, 0x38, 0x3a, 0x9c, 0x11,
	0xbf, 0x38, 0x70, 0xfe, 0x35, 0xea, 0xe6, 0x88, 0xef, 0x12, 0xb7, 0x75, 0xa3, 0x9d, 0xc3, 0x1b,
	0xfd, 0x2e, 0xf3, 0xe2, 0x33, 0x78, 0x3f, 0x61, 0x4a, 0xcf, 0x59, 0x74, 0x33, 0x13, 0x99, 0xca,
	0x53, 0x2c, 0xc4, 0x75, 0xe9, 0x01, 0xee, 0x85, 0xe0, 0xa5, 0x2c, 0xcb, 0x59, 0x32, 0x13, 0x69,
	0xca, 0x75, 0x69, 0xe1, 0xa2, 0xcf, 0x7b, 0x32, 0xa6, 0x72, 0x54, 0xd1, 0x8b, 0x44, 0xbc, 0x99,
	0x69, 0x99, 0x58, 0xbd, 0x5d, 0x5a, 0x87, 0x82, 0xdf, 0x1d, 0x78, 0x52, 0x27, 0xe4, 0xe1, 0x24,
	0x26, 0x35, 0x89, 0x43, 0x70, 0xcb, 0x17, 0x83, 0xb2, 0xde, 0x3e, 0x99, 0x78, 0xe1, 0xc1, 0x43,
	0x83, 0xee, 0xbf, 0x69, 0x5d, 0xd1, 0xc1, 0xc1, 0x6c, 0x0b, 0xe0, 0x34, 0xe5, 0xd9, 0x2b, 0x9e,
	0x72, 0x6d, 0x87, 0x57, 0xe1, 0xf4, 0x06, 0xd6, 0xdd, 0xbb, 0xf9, 0xc2, 0xec, 0x69, 0x1e, 0x22,
	0xcf, 0x93, 0xdd, 0x08, 0xad, 0x43, 0x35, 0x43, 0x2d, 0x12, 0xf1, 0xc6, 0x0e, 0xd1, 0xca, 0x50,
	0x06, 0x0a, 0xfe, 0x20, 0x70, 0x51, 0xa7, 0xfc, 0x9f, 0xcf, 0x8b, 0x77, 0x7a, 0x35, 0x34, 0x0c,
	0xd7, 0x6f, 0x1b, 0xee, 0x5f, 0x58, 0x2a, 0xf8, 0x89, 0xc0, 0x87, 0xcd, 0x06, 0xfe, 0x97, 0xa9,
	0x3b, 0xfd, 0x0a, 0xbe, 0x10, 0x72, 0x15, 0xb2, 0x0d, 0x8b, 0xd6, 0x18, 0xea, 0xfc, 0x1a, 0xd3,
	0xdb, 0x30, 0x12, 0x12, 0xaf, 0x99, 0x2a, 0xdf, 0xa7, 0xd7, 0xf9, 0x32, 0x5c, 0x61, 0x86, 0x92,
	0x69, 0x8c, 0xa7, 0xa7, 0x33, 0x4b, 0x66, 0xf1, 0x8e, 0x7d, 0x49, 0xde, 0x12, 0xf2, 0x2b, 0x21,
	0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xb0, 0x3b, 0x13, 0xd8, 0x0a, 0x00, 0x00,
}
